cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'thoughtbot/formulae'
tap '1password/tap'

brew 'ack'
brew 'asdf'
brew 'coreutils'
# brew 'ctags'
brew 'diff-so-fancy'
brew 'direnv'
brew 'fzf'
brew 'git'
brew 'go'
# brew 'graphviz'
# brew 'helm'
brew 'jq'
brew 'jq'
brew 'kubectl'
brew 'yh'
brew 'postgres'
# brew 'python3'
brew 'rcm'
brew 'rg'
brew 'selecta'
brew 'starship'
brew 'the_silver_searcher'
brew 'wget'

cask 'hammerspoon'
cask '1password-cli'
# cask 'ngrok'
# cask 'google-cloud-sdk'
# cask 'dbeaver-community'
# cask 'oracle-jdk'
