cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'thoughtbot/formulae'
tap '1password/tap'
tap 'homebrew/cask-fonts'

brew 'ack'
brew 'asdf'
brew 'coreutils'
# brew 'ctags'
brew 'git-delta'
brew 'difftastic'
brew 'direnv'
brew 'fzf'
brew 'git'
brew 'go'
# brew 'graphviz'
# brew 'helm'
brew 'jq'
brew 'jq'
brew 'kubectl'
brew 'yh'
brew 'postgres'
# brew 'python3'
brew 'rcm'
brew 'rg'
brew 'selecta'
brew 'starship'
brew 'the_silver_searcher'
brew 'wget'

cask 'hammerspoon'
cask '1password-cli'
cask 'font-victor-mono'
# cask 'ngrok'
# cask 'google-cloud-sdk'
# cask 'dbeaver-community'
# cask 'oracle-jdk'
