# Examples
#
# [default]
# extend-ignore-identifiers-re = [
#   # *sigh* this just isn't worth the cost of fixing
#   "AttributeID.*Supress.*",
# ]

# [default.extend-identifiers]
# # *sigh* this just isn't worth the cost of fixing
# AttributeIDSupressMenu = "AttributeIDSupressMenu"

# [default.extend-words]
# # Don't correct the surname "Teh"
# teh = "teh"

# # typos --type-list
# [type.po]
# extend-glob = ["*.po"]
# check-file = false

[files]
extend-exclude = ["argo_all_k8s_kustomize_schema.json"]
