[tools]
rust = "latest"
"cargo:eza" = "latest"
"cargo:tealdeer" = "latest"
"cargo:dotenvy" = "latest"

[settings]
experimental = true

env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`
