[tools]
"cargo:dotenvy" = "latest"
"cargo:eza" = "latest"
"cargo:tealdeer" = "latest"
"cargo:typos-cli" = "latest"
elixir = "1.17.2-otp-27"
erlang = "27.0.1"
nodejs = "24.3.0"
python = "3.12.2"
ruby = "3.0.2"
rust = "latest"

[settings]
experimental = true

env_file = '.env.local' # load env vars from a dotenv file, see `MISE_ENV_FILE`
